### PR TITLE
add octo-sts to mono to be able to open pull requests

### PR DESCRIPTION
**Pull request by cpanato**
not sure if the subject is the correct one as the job is a workflow run https://github.com/chainguard-dev/mono/blob/main/.github/workflows/release-helm-charts.yaml#L9

https://github.com/chainguard-dev/mono/actions/workflows/release-helm-charts.yaml

### CODE REVIEW

**Review by mattmoor — APPROVED** [review]
Did you enable the App on this repo?

**Comment by cpanato** [comment]
> Did you enable the App on this repo?

the app is set per repo? i will take a look

**Comment by mattmoor** [comment]
I scoped it to the homebrew repo initially to be safe, but we can expand it to include this for sure.

**Comment by mattmoor** [comment]
I added it.

**Pull request merged**
